### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by tariktesfa** [Gegardus/space-travelers-hub#26]
Hello there 👋 

We have copied the kanban board to our project and you can find it from [here ](https://github.com/Gegardus/space-travelers-hub/projects/1). We are a team of 3. i.e.

- [Vahan ](https://github.com/Gegardus)
- [Selma](https://github.com/selma-belhadj)
- [Tarikwa ](https://github.com/tariktesfa)

**Comment by rustam-tolipov** [comment]
## Hello team 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
